version: "3.5"
services:
  api-the-coffee-class:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TheCoffeeClass-Api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    ports:
      - 3008:3008
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gateway
networks:
  gateway:
    name: gateway
    driver: bridge
